FROM python:3.11-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

# install deps ONLY
RUN pip install --no-cache-dir --prefix=/install --only-binary=:all: \
    aiohttp \
    pydantic \
    pydantic-settings \
    orjson \
    tenacity \
    structlog \
    confluent-kafka

# ---- runtime ----
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    librdkafka1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /install /usr/local
COPY rpcstream ./rpcstream

# clean cache (extra polish)
RUN find /usr/local -type d -name "__pycache__" -exec rm -r {} + || true

CMD ["python", "block_pipeline_realtime.py"]